FROM ubuntu:24.04
MAINTAINER shor-tcut

ARG ENVIRONMENT
ARG APP_PORT
ARG PHP_VERSION

ARG WWW_BASE_DIR
ARG PROJECT_ROOT_DOCKER

ENV DEBIAN_FRONTEND noninteractive
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/www/application/var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

RUN ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone

RUN apt-get update && apt-get install -yq --no-install-recommends \
    vim \
    curl \
    zip \
#    locales \
    unzip \
    apache2 \
    libapache2-mod-php \
    imagemagick \
    imagemagick-6-common \
    ffmpeg \
    ghostscript \
    libimage-exiftool-perl \
    inkscape \
    php \
    php-common \
    php-cli \
    php-intl \
    php-dom \
    php-gd \
    php-mbstring \
    php-ldap \
    php-imap \
    php-bcmath \
    php-mysqli \
    php-zip \
    php-curl \
    php-xml \
    php-apcu \
    7zip \
    antiword \
    poppler-utils \
    cron

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# check if you all need
RUN a2enmod  \
    rewrite \
    expires  \
    setenvif  \
#    proxy  \
#    proxy_http  \
#    proxy_html  \
    xml2enc  \
    ssl  \
    headers

# Install composer
# COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Set locales
#RUN locale-gen \
#    de_DE.utf8 \
#    en_GB.utf8 \
#    en_US.utf8
#
#RUN update-locale LANG=de_DE.utf8

RUN test -d ${PROJECT_ROOT_DOCKER} || mkdir -p ${PROJECT_ROOT_DOCKER}
RUN cd ${PROJECT_ROOT_DOCKER} \
    && chown ${APACHE_RUN_USER}.${APACHE_RUN_GROUP} "${WWW_BASE_DIR}"

COPY ./app/resources/bashrc ${WWW_BASE_DIR}/.bashrc
COPY ./app/resources/entrypoint.${ENVIRONMENT}.sh /entrypoint.sh

COPY ./app/resources/ports.${ENVIRONMENT}.conf /etc/apache2/ports.conf
COPY ./app/resources/php.${ENVIRONMENT}.ini /etc/php/${PHP_VERSION}/apache2/php.ini
COPY ./app/resources/php.${ENVIRONMENT}.ini /etc/php/${PHP_VERSION}/cli/php.ini

RUN rm /etc/apache2/sites-available/* && rm /etc/apache2/sites-enabled/*
COPY ./app/resources/apache.${ENVIRONMENT}.conf /etc/apache2/sites-available/application.conf
#COPY ./app/resources/apache.${ENVIRONMENT}.https.conf /etc/apache2/sites-available/application.https.conf

COPY ./app/resources/crontab.${ENVIRONMENT} /etc/cron.d/mddb
RUN chown root:root /etc/cron.d/mddb && chmod 644 /etc/cron.d/mddb
RUN usermod --shell /usr/bin/bash "${APACHE_RUN_USER}"

RUN chown ${APACHE_RUN_USER}.${APACHE_RUN_GROUP} ${WWW_BASE_DIR}/.bashrc
RUN chmod +x /entrypoint.sh

RUN a2ensite application
#RUN a2ensite application.https

WORKDIR ${PROJECT_ROOT_DOCKER}
EXPOSE ${APP_PORT}
ENTRYPOINT ["/entrypoint.sh"]

CMD ["apache2ctl", "-D", "FOREGROUND"]